#line 2 "source/lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_acclist[375] =
    {   0,
       75,   73,   74,    1,   73,   74,   72,   74,   73,   74,
       73,   74,   72,   73,   74,   73,   74,   72,   73,   74,
       73,   74,   73,   74,   72,   73,   74,   70,   73,   74,
       70,   73,   74,   73,   74,   60,   71,   73,   74,   61,
       71,   73,   74,   62,   71,   73,   74,   71,   73,   74,
       71,   73,   74,   71,   73,   74,   71,   73,   74,   71,
       73,   74,   59,   71,   73,   74,   71,   73,   74,   71,
       73,   74,   71,   73,   74,   71,   73,   74,   71,   73,
       74,   71,   73,   74,   56,   71,   73,   74,   71,   73,
       74,   71,   73,   74,   60,   71,   73,   74,   62,   71,

       73,   74,   71,   73,   74,   71,   73,   74,   71,   73,
       74,   71,   73,   74,   71,   73,   74,   71,   73,   74,
       71,   73,   74,   71,   73,   74,   71,   73,   74,   56,
       71,   73,   74,   71,   73,   74,   71,   73,   74,   66,
       70,   70,   64,   65,   69,   70,   70,   69,   68,    2,
       71,   71,   71,   71,   68,   71,   71,   52,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   16,   71,   71,
       71,   71,   71,   57,   71,   71,   71,   71,   71,   71,
       63,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   16,   71,   71,   71,
       71,   71,   57,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   67,   67,    4,   71,    3,   71,   15,   71,
       71,   71,   71,   48,   71,   49,   71,   45,   71,   32,
       71,   33,   71,   46,   71,   47,   71,   19,   71,   44,
       71,   42,   71,   43,   71,   27,   71,   71,   13,   71,
       11,   71,    8,   71,   41,   71,    7,   71,   40,   71,
       18,   71,   25,   71,   37,   71,   71,   10,   71,   39,
       71,   58,   71,   14,   71,   12,   71,   71,    6,   71,

        9,   71,    5,   71,   71,   17,   71,    4,   71,    3,
       71,   15,   71,   71,   71,   71,   71,   13,   71,   11,
       71,   71,   14,   71,   12,   71,   71,    6,   71,    5,
       71,   71,   17,   71,   21,   71,   20,   71,   24,   71,
       50,   71,   71,   51,   71,   34,   71,   30,   71,   28,
       71,   36,   71,   31,   71,   29,   71,   35,   71,   23,
       71,   22,   71,   38,   71,   26,   71,   71,   71,   71,
       54,   71,   55,   53
    } ;

static yyconst short int yy_accept[256] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   16,
       18,   21,   23,   25,   28,   31,   34,   36,   40,   44,
       48,   51,   54,   57,   60,   63,   67,   70,   73,   76,
       79,   82,   85,   89,   92,   95,   99,  103,  106,  109,
      112,  115,  118,  121,  124,  127,  130,  134,  137,  140,
      140,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      142,  143,  143,  144,  145,  145,  146,  147,  148,  148,
      149,  150,  150,  151,  152,  153,  154,  155,  157,  158,
      160,  161,  162,  163,  164,  165,  166,  167,  168,  169,
      170,  171,  172,  173,  174,  175,  176,  177,  178,  180,

      181,  182,  183,  184,  186,  187,  188,  189,  190,  191,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      213,  214,  215,  216,  217,  219,  220,  221,  222,  223,
      225,  226,  227,  228,  229,  230,  231,  232,  233,  233,
      233,  233,  233,  234,  235,  235,  237,  239,  241,  242,
      243,  244,  246,  248,  250,  252,  254,  256,  258,  260,
      262,  264,  266,  268,  269,  271,  273,  275,  277,  279,
      281,  283,  285,  287,  288,  290,  292,  294,  296,  298,
      299,  301,  303,  305,  306,  308,  310,  312,  314,  315,

      316,  317,  318,  320,  322,  323,  325,  327,  328,  330,
      332,  333,  335,  335,  335,  335,  335,  337,  339,  341,
      343,  344,  346,  348,  350,  352,  354,  356,  358,  360,
      362,  364,  366,  368,  369,  369,  369,  369,  369,  370,
      371,  371,  371,  371,  371,  373,  373,  373,  373,  373,
      373,  374,  374,  375,  375
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    7,    6,
        6,    6,    8,    6,    9,   10,    1,   11,   12,   13,
       13,   13,   13,   13,   13,   13,   13,    6,   14,    1,
        6,    1,    1,    6,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   25,   39,
        6,   40,    6,    1,   25,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   25,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       25,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        3,    3,    3,    3,    3,    3,    4,    5,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[261] =
    {   0,
        0,    0,  389,  390,  390,  390,   61,   48,  390,  348,
       56,   61,   54,   66,   70,   73,  384,  111,  149,  371,
      348,  356,    0,    0,  368,    0,  115,   61,   69,  353,
      349,   71,   84,  166,  351,   43,  338,  316,  324,  335,
      127,  154,   59,  321,  317,   55,   92,  158,  319,   85,
      390,  369,  352,  342,  324,  315,  360,  359,    0,  134,
        0,  317,  390,  390,  172,  316,  204,    0,  315,  314,
      390,  358,  390,    0,  130,    0,  342,    0,  333,    0,
      340,  331,   58,  132,  189,  337,  321,  324,  101,  190,
      330,  337,  317,  328,  323,  312,  321,  155,  323,  315,

      311,  310,  308,  318,  306,  317,  302,  320,  308,    0,
      319,  304,  301,  160,  288,  280,  286,  278,  166,  165,
      167,  283,  268,  271,   43,  183,  276,  283,  264,  274,
      270,  259,  268,  172,  269,  262,  258,  257,  255,  264,
      253,  263,  249,  266,  255,  265,  251,  248,  284,  286,
      256,  258,  390,  293,    0,  276,  275,  274,  270,  277,
      260,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  275,  269,  268,    0,    0,    0,    0,
        0,    0,    0,  268,    0,    0,    0,  266,  265,  268,
      263,    0,  262,  267,  260,  233,  232,  231,  228,  234,

      218,  232,  226,  225,  225,  223,  222,  225,  220,  219,
      224,  217,  238,  238,  211,  202,    0,    0,    0,    0,
      229,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  195,  224,  203,  196,  176,  215,  188,
      216,  214,  187,  184,    0,  154,  158,  118,  113,  109,
      390,   60,  390,  390,  241,  246,   67,  249,  254,  257
    } ;

static yyconst short int yy_def[261] =
    {   0,
      254,    1,  254,  254,  254,  254,  255,  254,  254,  256,
      257,  257,  254,  257,  258,  258,  259,  260,  260,   19,
       19,   19,   19,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,   19,   19,   19,   19,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  255,
      254,  255,  254,  254,  254,  254,  254,  256,   14,   16,
       16,  258,  254,  254,  258,  258,   65,   16,  258,  258,
      254,  259,  254,   19,   19,  260,  260,  260,   19,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,   19,  260,   19,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  254,  254,
      254,  254,  254,  254,   65,   19,   19,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,   19,   19,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  254,  254,  254,  254,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  254,  254,  254,  254,  260,  260,
      254,  254,  254,  254,  260,  254,  254,  254,  254,  254,
      254,  254,  254,    0,  254,  254,  254,  254,  254,  254
    } ;

static yyconst short int yy_nxt[455] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   24,   28,   29,   30,   31,   32,
       24,   33,   34,   24,   24,   24,   24,   35,   24,    4,
       36,   19,   37,   38,   39,   23,   24,   40,   26,   41,
       42,   43,   44,   45,   46,   24,   47,   48,   24,   24,
       24,   24,   49,   24,   51,   53,   59,   60,   61,   62,
       54,   59,   60,   61,  162,   63,   59,   65,   91,   64,
       67,   67,   68,   68,   68,   68,  114,  170,   51,   92,
      163,   55,   93,   94,   95,  115,   56,   96,  102,  100,

       52,   63,  103,   97,   64,  101,  170,   66,  136,  131,
      104,   70,  132,  253,  137,  105,  106,   71,  133,  170,
       71,   74,   74,   74,   52,   74,   74,   74,   75,   74,
       74,   83,  138,   84,   85,   86,  139,  253,   77,  170,
       87,   88,   89,  140,   67,   67,  156,  157,  141,  142,
       90,   74,   74,   74,   74,   74,   74,  251,   78,   74,
       74,   74,  164,   74,   74,   74,   74,   74,   74,  119,
      164,  120,  121,  122,  252,   70,  251,  123,  124,  125,
      107,  108,  155,  155,  180,  250,  109,  126,  181,   74,
       74,   74,   74,   74,   74,  110,   78,  127,  143,  144,

      111,  112,  196,  197,  145,  165,  171,  128,  162,  165,
      129,  130,  110,   70,   67,   67,   68,  146,  147,   71,
      164,  166,  172,  163,  166,  171,  180,  249,  164,  248,
      181,  247,  246,  245,  245,  244,  243,  242,  241,  240,
      172,   50,   50,   50,   50,   50,   57,  239,   57,   57,
       57,   69,  238,   69,   72,   72,   72,   72,   72,   76,
       76,   76,  237,  236,  235,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  234,  220,  219,
      218,  217,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  153,

      216,  215,  214,  213,  212,  211,  210,  192,  209,  208,
      207,  206,  187,  186,  185,  205,  183,  182,  179,  178,
      177,  204,  203,  202,  173,  169,  168,  167,  201,  200,
      199,  198,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  179,  178,  177,  176,
      175,  174,  173,  169,  168,  167,  161,  160,  159,  158,
       73,   71,   71,   71,   71,  154,  153,  152,  151,  150,
      149,  254,  148,  135,  134,  118,  117,   80,  116,  113,
       99,   98,   82,   81,   80,   79,   73,   58,  254,    3,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254
    } ;

static yyconst short int yy_chk[455] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,   11,   11,   11,  257,
        8,   12,   12,   12,   83,   13,   14,   14,   28,   13,
       15,   15,   15,   16,   16,   16,   36,  125,   50,   28,
       83,    8,   28,   28,   29,   36,    8,   29,   33,   32,

        7,   13,   33,   29,   13,   32,  125,   14,   46,   43,
       33,   15,   43,  252,   46,   33,   33,   15,   43,   89,
       16,   18,   18,   18,   50,   18,   18,   18,   18,   18,
       18,   27,   47,   27,   27,   27,   47,  250,   18,   89,
       27,   27,   27,   47,   60,   60,   75,   75,   47,   47,
       27,   18,   18,   18,   18,   18,   18,  249,   18,   19,
       19,   19,   84,   19,   19,   19,   19,   19,   19,   41,
       84,   41,   41,   41,  248,   60,  247,   41,   41,   41,
       34,   34,   65,   65,   98,  246,   34,   41,   98,   19,
       19,   19,   19,   19,   19,   34,   19,   42,   48,   48,

       34,   34,  114,  114,   48,   85,   90,   42,  119,  121,
       42,   42,   48,   65,   67,   67,   67,   48,   48,   65,
      120,   85,   90,  119,  121,  126,  134,  244,  120,  243,
      134,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      126,  255,  255,  255,  255,  255,  256,  221,  256,  256,
      256,  258,  216,  258,  259,  259,  259,  259,  259,  260,
      260,  260,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  191,  190,  189,  188,  184,
      176,  175,  174,  161,  160,  159,  158,  157,  156,  154,

      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  133,  132,
      131,  130,  129,  128,  127,  124,  123,  122,  118,  117,
      116,  115,  113,  112,  111,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   97,   96,   95,   94,
       93,   92,   91,   88,   87,   86,   82,   81,   79,   77,
       72,   70,   69,   66,   62,   58,   57,   56,   55,   54,
       53,   52,   49,   45,   44,   40,   39,   38,   37,   35,
       31,   30,   25,   22,   21,   20,   17,   10,    3,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
#include <stdio.h>
#include <string.h>
#include "ast.h"
#include "y.tab.h"

void count();
char parseEscapeSeq(char *str);

unsigned int line = 1;
unsigned int character = 1;
#line 615 "source/lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 16 "lexer.l"


#line 769 "source/lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 255 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 390 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 18 "lexer.l"
count();
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 20 "lexer.l"
count();
	YY_BREAK

    // Instructions
    // A-type

case 3:
YY_RULE_SETUP
#line 25 "lexer.l"
{ count(); return ADD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 26 "lexer.l"
{ count(); return ADC;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "lexer.l"
{ count(); return SUB;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 28 "lexer.l"
{ count(); return SBC;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 29 "lexer.l"
{ count(); return MUL;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 30 "lexer.l"
{ count(); return MLL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 31 "lexer.l"
{ count(); return SGN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "lexer.l"
{ count(); return RAS;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 33 "lexer.l"
{ count(); return LSH;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 34 "lexer.l"
{ count(); return RSH;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "lexer.l"
{ count(); return LRT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "lexer.l"
{ count(); return RRT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "lexer.l"
{ count(); return AND;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "lexer.l"
{ count(); return OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "lexer.l"
{ count(); return XOR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "lexer.l"
{ count(); return NOT;}
	YY_BREAK

    // J-type

case 19:
YY_RULE_SETUP
#line 44 "lexer.l"
{ count(); return JMP;}
	YY_BREAK

    // I-type

case 20:
YY_RULE_SETUP
#line 48 "lexer.l"
{ count(); return ADDI;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "lexer.l"
{ count(); return ADCI;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "lexer.l"
{ count(); return SUBI;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "lexer.l"
{ count(); return SBCI;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "lexer.l"
{ count(); return ANDI;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "lexer.l"
{ count(); return ORI;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "lexer.l"
{ count(); return XORI;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "lexer.l"
{ count(); return LDI;}
	YY_BREAK

    // SI-type

case 28:
YY_RULE_SETUP
#line 59 "lexer.l"
{ count(); return LSHI;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "lexer.l"
{ count(); return RSHI;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "lexer.l"
{ count(); return LRTI;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "lexer.l"
{ count(); return RRTI;}
	YY_BREAK

    // F-type

case 32:
YY_RULE_SETUP
#line 66 "lexer.l"
{ count(); return JFC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "lexer.l"
{ count(); return JFS;}
	YY_BREAK

    // LS-type

case 34:
YY_RULE_SETUP
#line 71 "lexer.l"
{ count(); return LOAD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "lexer.l"
{ count(); return SAVE;}
	YY_BREAK

    // SP-type

case 36:
YY_RULE_SETUP
#line 76 "lexer.l"
{ count(); return PUSH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "lexer.l"
{ count(); return POP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "lexer.l"
{ count(); return SVPC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "lexer.l"
{ count(); return RET;}
	YY_BREAK

    // Macros

case 40:
YY_RULE_SETUP
#line 83 "lexer.l"
{ count(); return NOP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "lexer.l"
{ count(); return MOV;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "lexer.l"
{ count(); return JVC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "lexer.l"
{ count(); return JVS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "lexer.l"
{ count(); return JNE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "lexer.l"
{ count(); return JEQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "lexer.l"
{ count(); return JGE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "lexer.l"
{ count(); return JLT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "lexer.l"
{ count(); return JCC;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "lexer.l"
{ count(); return JCS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "lexer.l"
{ count(); return CALL;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "lexer.l"
{ count(); return HALT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "lexer.l"
{ count(); return DW;}
	YY_BREAK

    // Directives

case 53:
YY_RULE_SETUP
#line 99 "lexer.l"
{ count(); return DEFMACRO;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 100 "lexer.l"
{ count(); return ENDDEF;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 101 "lexer.l"
{ count(); return INCLUDE;}
	YY_BREAK

    // Argument types

case 56:
YY_RULE_SETUP
#line 105 "lexer.l"
{ count(); return REG;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "lexer.l"
{ count(); return REGMEM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "lexer.l"
{ count(); return REGMEMIMM;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "lexer.l"
{ count(); return IMM;}
	YY_BREAK

    // Register

case 60:
YY_RULE_SETUP
#line 112 "lexer.l"
{ count(); return A;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "lexer.l"
{ count(); return B;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "lexer.l"
{ count(); return C;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "lexer.l"
{ count(); return SP;}
	YY_BREAK

    // High and low bytes

case 64:
YY_RULE_SETUP
#line 119 "lexer.l"
{ count(); return HIGH;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 120 "lexer.l"
{ count(); return LOW;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 122 "lexer.l"
{ count(); yylval.text = strdup(yytext); return STRING;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 123 "lexer.l"
{ count(); yylval.iVal = parseEscapeSeq(yytext); return CHAR;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 124 "lexer.l"
{ count(); yylval.iVal = strtoul(yytext, NULL, 16) & 0xFFFFFFFF; return HEX;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 125 "lexer.l"
{ count(); yylval.iVal = strtoul(yytext, NULL, 2) & 0xFFFFFFFF; return BINARY;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 126 "lexer.l"
{ count(); yylval.iVal = strtol(yytext, NULL, 10) & 0xFFFFFFFF; return DECIMAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 127 "lexer.l"
{ count(); yylval.text = strdup(yytext); return IDENTIFIER;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 "lexer.l"
{ count(); return yytext[0];}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "lexer.l"
{}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 132 "lexer.l"
ECHO;
	YY_BREAK
#line 1270 "source/lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 255 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 255 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 254);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 132 "lexer.l"


void count() {
    //if(!strcmp(yytext, "\n"))
    //    line++;
    //character += yyleng;
}

char parseEscapeSeq(char *str) {
    if (str[1] != '\\')
        return str[1];
    switch (str[2]) {
        case 'a': return '\a';
        case 'b': return '\b';
        case 'n': return '\n';
        case 't': return '\t';
        case 'v': return '\v';
        case '0': return '\0';
        default: return str[2];
    }
}
